// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQI82qbIo_W2Wvp-_qlPU0UYLJXZj2gGQ',
    appId: '1:724514251476:web:bf6ca6312d82e896bd5141',
    messagingSenderId: '724514251476',
    projectId: 'libros-favg',
    authDomain: 'libros-favg.firebaseapp.com',
    storageBucket: 'libros-favg.appspot.com',
    measurementId: 'G-7JG6Z9TDH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6BTsf2pPP898UZwJw7N_yx_mJ72DhbUY',
    appId: '1:724514251476:android:b926e13ab18462b5bd5141',
    messagingSenderId: '724514251476',
    projectId: 'libros-favg',
    storageBucket: 'libros-favg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYTe2IgbjwwKtwY2Lof6nLitk7FEmBQ8o',
    appId: '1:724514251476:ios:cff47b0fc78aea49bd5141',
    messagingSenderId: '724514251476',
    projectId: 'libros-favg',
    storageBucket: 'libros-favg.appspot.com',
    iosClientId: '724514251476-mtc0i2gnru0qfs7mnsb3h2mcddok2m54.apps.googleusercontent.com',
    iosBundleId: 'com.favg.libros',
  );
}
